In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.decomposition import PCA,SparsePCA
import numpy as np
import re
from sklearn import metrics
from scipy.stats import uniform, truncnorm, randint
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import confusion_matrix
from sklearn import tree
from sklearn.utils import class_weight
import gensim
from sklearn.neighbors import KNeighborsClassifier
from gensim.models import KeyedVectors, Word2Vec, FastText
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix,classification_report

In [2]:
X_link = 'https://raw.githubusercontent.com/python-for-ml/sent-analysis/master/X.csv'
X = pd.read_csv(X_link, header = None).to_numpy()

In [3]:
label_link = 'https://raw.githubusercontent.com/python-for-ml/sent-analysis/master/label.csv'
label = pd.read_csv(label_link, header = None)
label = label.to_numpy().reshape([1, len(label)])[0]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,label, test_size=0.2)

In [5]:
class_weights = class_weight.compute_class_weight('balanced',np.unique(y_train),y_train)
class_weights

array([1.45882353, 0.7607362 ])

In [6]:
param_grid = dict(n_neighbors=[25,32,48])
print(param_grid)
clf = GridSearchCV(KNeighborsClassifier(), param_grid, cv=10, scoring='accuracy')
clf_results=clf.fit(X_train, y_train)

{'n_neighbors': [25, 32, 48]}


In [7]:
print(clf_results)
clf_results.cv_results_

GridSearchCV(cv=10, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [25, 32, 48]}, pre_dispatch='2*n_jobs',
             refit=True, return_train_score=False, scoring='accuracy',
             verbose=0)


{'mean_fit_time': array([0.47669492, 0.47946646, 0.46514623]),
 'std_fit_time': array([0.02290693, 0.01619714, 0.00878465]),
 'mean_score_time': array([3.29668372, 3.33440051, 3.33403676]),
 'std_score_time': array([0.06397029, 0.05914865, 0.05610091]),
 'param_n_neighbors': masked_array(data=[25, 32, 48],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 25}, {'n_neighbors': 32}, {'n_neighbors': 48}],
 'split0_test_score': array([0.67626728, 0.67396313, 0.67165899]),
 'split1_test_score': array([0.72580645, 0.7235023 , 0.72004608]),
 'split2_test_score': array([0.69585253, 0.69815668, 0.71082949]),
 'split3_test_score': array([0.73271889, 0.73617512, 0.73041475]),
 'split4_test_score': array([0.69815668, 0.69815668, 0.70391705]),
 'split5_test_score': array([0.6843318 , 0.68087558, 0.68663594]),
 'split6_test_score': array([0.71313364, 0.71889401, 0.71198157]),
 'split7_test_score': array([0.7062212 , 0.70852535, 

In [8]:
y_pred = clf.predict(X_test)
y_pred

array([1., 1., 1., ..., 1., 0., 1.])

In [9]:
conf_mat = confusion_matrix(y_test, y_pred)
print("Confusion matrix:\n", conf_mat)
print("Accuracy  :",metrics.accuracy_score(y_test, y_pred))
print("Precision :",metrics.precision_score(y_test,y_pred))
print("F1-Score  :",metrics.f1_score(y_test,y_pred))
print("Recall    :",metrics.recall_score(y_test,y_pred))

Confusion matrix:
 [[ 203  547]
 [ 111 1310]]
Accuracy  : 0.6969138645785352
Precision : 0.7054388799138396
F1-Score  : 0.7992678462477122
Recall    : 0.9218859957776214
